joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - Hip
    - Knee